### ISSUE TITLE
run example and got error

### ISSUE THREAD

**Issue by chyyuu** [rcore-os/virtio-drivers#1]
I change target from  riscv64imac-unknown-none-elf to   riscv64gc-unknown-none-elf （seems newer）, and use rustc 1.51-nightly, qemu-5.0
Compiling OK.
But when `make qemu`, I got runtime error:

"Guest has not initialized the display (yet)."

How to fix it?

**Comment by x213212** [comment]
curl https://sh.rustup.rs -sSf | sh
source "$HOME/.cargo/env"
rustup target install riscv64gc-unknown-none-elf
