### ISSUE TITLE
Unable to build with feature `tcp` enabled

### ISSUE THREAD

**Issue by GyulyVGC** [rcore-os/virtio-drivers#120]
Hi guys, I'm trying to run the `x86_64` example on a [Proxmox](https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines) QEMU KVM.

If I set the `tcp` feature to `on`, the compilation fails as reported below.

![Screenshot 2023-11-30 at 17 18 19](https://github.com/rcore-os/virtio-drivers/assets/100347457/7118a75a-cfa2-404a-b477-f87c0d56fc76)

Any idea of the possible cause?

Thanks in advance for your availability.

**Comment by qwandor** [comment]
Fixed in #119.
