### ISSUE TITLE
编码建议

### ISSUE THREAD

**Issue by putao0525** [rcore-os/virtio-drivers#150]
清华大学这么牛逼组织，能不能持续迭代一些基础系统的包？ 操作系统以后的趋势，就是由无数个包组织。 长期坚持必然能立于世界之巅。
不要很狭隘的放到rcore下面去，目标不是一个操作系统，而是一个可以生产操作系统的工具集合。 我们要的是天下， 不是一城一池。
工程里面不要有一些第几章这种字样，要极为严谨。

**Comment by wangrunji0408** [comment]
您好。我们也认同操作系统应该切成很多独立的、可复用的库。正因如此，我们已经陆续开放了一些基础库，本仓库就是其中之一。您可以在[我们社区的首页](https://github.com/rcore-os)找到更多仓库和介绍。

至于为什么都放到 rcore-os 这个组织，是因为它们都起源于 rCore 及后续项目，放在同一个组织下方便管理和维护。rCore 只是 众多用 Rust 写操作系统社区的一员。它不影响开发者在遵守开源协议的前提下，自由使用、修改和 fork 项目代码。此外，我们也欢迎外部开发者共同建设生态。例如本项目当前就是由 qwandor 维护的。

> 工程里面不要有一些第几章这种字样，要极为严谨。

如发现有不当之处，请您指出具体的代码位置，以帮助我们改进项目。谢谢。
