### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by qwandor** [rcore-os/virtio-drivers#19]
I would like to use this crate in a project I'm working on, and so would like to be able to get a stable version from crates.io. I'm happy to publish it myself, but let me know if you'd prefer to.

**Comment by wangrunji0408** [comment]
I did plan to publish it to crates.io from the beginning. But given the unstable API, I never took an action.
If you think it is time, feel free to publish it! Just don't forget to add me as an owner :)

P.S. Given that I won't be working on embedded-related development for a while, I'd like to invite you as a maintainer of this crate. Please let me know if you are interested 😄

**Comment by qwandor** [comment]
Thanks! I'm happy to be a maintainer. There are definitely API changes that will be needed, but a published 0.1 version would be useful to me as a starting point at least. I'll push that now.

**Comment by qwandor** [comment]
Published, and pushed a tag to this repository.
