### ISSUE TITLE
compilation error due to the use of spin_loop

### ISSUE THREAD

**Issue by CriusT** [rcore-os/virtio-drivers#3]
When I run the code in ch7 without any modification, I ran into a compilation error. I think '#![feature(renamed_spin_loop)]' should be added to lib.rs.
My rust version is rustc 1.46.0-nightly (50fc24d8a 2020-06-25)
![image](https://user-images.githubusercontent.com/40891932/121282767-a0d47200-c90c-11eb-8bc7-935a488b475b.png)

**Comment by wangrunji0408** [comment]
Your toolchain version is a bit old. The latest nightly toolchain does not require this feature.

This crate is not intended to be compatible with the old toolchain. Sorry for this.
