### ISSUE TITLE
a bug in blk::read/write_block_nb

### ISSUE THREAD

**Issue by wyfcyx** [rcore-os/virtio-drivers#7]
In these methods, we allocate a `BlkReq` instance on the stackframe. The memory block which the `BlkReq` instance resides in will be reused after the methods return, and there is a possibility that the virtio device is also accessing it at the same time, leading to a data race. Mention that the blocking version of there methods do not have this problem since when the methods returns and the `BlkReq` is deallocated, it can be guaranteed that the virtio device has completed handling the request before.

I have no idea how to fix it yet.

**Comment by qwandor** [comment]
I plan to fix this as part of some other improvements to buffer handling I'm working on. I'll send a PR soon.

**Comment by wyfcyx** [comment]
This bug has been fixed in #40. Close it.
