### ISSUE TITLE
Network driver issues on multicore systems

### ISSUE THREAD

**Issue by CtrlZ233** [rcore-os/virtio-drivers#77]
Hello, I'd like to ask if this package supports network drivers on multicore systems. When I create multiple TCP connections using the send interface of virtio-net on a multicore machine, the captured packets in tcpdump are incomplete and disordered.

```rust
let responese = "response from server";
// write a response
syscall::write!(client_fd, responese.as_bytes());
```
![image](https://user-images.githubusercontent.com/50608896/235409507-68ef137f-bdf6-4329-90d7-507baa72be29.png)

Additionally, it works fine if there is only a single TCP connection.

**Comment by equation314** [comment]
Could your give a minimal example to reproduce the bug?

**Comment by CtrlZ233** [comment]
> Could you give a minimal example to reproduce the bug?

Sorry, I'm not sure if the issue is caused by how I'm using it or the driver code, so I'd like to ask if consideration was given to multi-core CPUs during the design of the virtio-net driver? I couldn't find any relevant descriptions in the documentation.

**Comment by equation314** [comment]
Multi-core support does not need special consideration if unsafe code is not used, but there may be bugs that we have not found.
