### ISSUE TITLE
is there any means to unload virtio driver?

### ISSUE THREAD

**Issue by theSprog** [rcore-os/virtio-drivers#98]
In the current version (as of 0.5.0), I noticed that this library does not provide a way to unload the virtio driver. I need to unload the driver in order to reload or use another driver in a given situation.

While the library provides the ability to load the driver, it lacks a way to unload it. I think adding support for unloading drivers would make the library more complete and flexible.

I would like to be able to dynamically load and unload virtio drivers within an application to allow flexibility to adjust as needed. Currently, the only way to uninstall a driver seems to be to restart the application or the OS（this way seem to be too rude）.

Please consider adding a function or method to uninstall the virtio driver to allow developers to uninstall the driver at runtime. This would add functionality and flexibility to the library and match the functionality of the loaded driver.

Thanks for your interest and contribution!

Additional information:

Library version: 0.5.0
Operating system: rcore-os，(yeah I'am following this os tutorial)

**Comment by qwandor** [comment]
Hello,
Dropping the driver will reset the queues if possible (the MMIO transport allows this but the PCI transport doesn't), free memory allocated by the driver, and then drop the transport. Dropping the transport will in turn reset the device by writing 0 to the status register.

Does that do what you want?

**Comment by theSprog** [comment]
yeah, I know.
That helps a lot, thank you so much
